Repository sun-horse/grace-shopper, pull requests merged in 2019-01, with the labels that each got.

#19 F/product model
  script/seed.js
  server/db/models/index.js
  server/db/models/product.js
  server/db/models/product.spec.js
Labels: in progress

#20 F/products route
  .package.json.swp
  server/api/index.js
  server/api/products.js
  server/api/products.spec.js
Labels: in progress

#18 F/products sub reducer
  client/store/index.js
  client/store/products.js
  client/store/products.spec.js
  client/store/user.spec.js
Labels: enhancement, help wanted

#27 fix: change page title to sun horse
  public/index.html
Labels: in progress

#33 F/product component
  client/components/all-products.js
  client/components/all-products.spec.js
  client/components/product.js
  client/components/product.spec.js
Labels: in progress

#32 F/cart reducer
  client/store/cart.js
  client/store/cart.spec.js
  client/store/index.js
Labels: in progress

#41 fix: code cleanup
  client/components/all-products.js
  client/components/index.js
  client/components/product.spec.js
Labels: in progress

#54 Product model fixes
  client/components/all-products.js
  client/components/all-products.spec.js
  client/components/navbar.spec.js
  client/components/product.js
  client/components/product.spec.js
  client/store/cart.spec.js
  client/store/products.spec.js
  script/seed.js
  server/db/models/product.js
Labels: in progress

#59 fix: link SunHorse header to /products
  client/components/navbar.js
Labels: in progress

#60 F/add cart button
  client/components/all-products.spec.js
  client/components/product.js
  client/components/product.spec.js
  client/store/cart.js
Labels: in progress

#63 F/order models
  script/seed.js
  server/db/models/index.js
  server/db/models/order.js
  server/db/models/order.spec.js
  server/db/models/orderProducts.js
Labels: in progress

#70 F/cart component
  client/components/AllProducts.js
  client/components/Cart.js
  client/components/Navbar.js
  client/components/Navbar.spec.js
  client/components/ProductCard.js
  client/components/ProductCard.spec.js
  client/components/index.js
  client/routes.js
  client/utils/index.js
  public/style.css
  server/db/models/product.js
Labels: help wanted

#79 F/order model
  README.md
  server/db/models/index.js
  server/db/models/order.js
  server/db/models/order.spec.js
  server/db/models/orderProduct.js
  server/db/models/orderProducts.js
Labels: in progress

#78 test: cart component
  client/components/Cart.js
  client/components/Cart.spec.js
  client/components/testData.js
Labels: in progress

#88 F/cart backend
  client/components/Navbar.js
  client/components/Navbar.spec.js
  client/components/ProductCard.js
  client/store/cart.js
  client/store/cart.spec.js
  client/store/products.js
  client/store/products.spec.js
  server/api/products.js
  server/api/users.js
Labels: in progress

#89 feat: set up bulma css
  client/app.js
  client/components/AllProducts.js
  client/components/Cart.js
  client/components/Navbar.js
  public/index.html
  public/style.css
Labels: in progress

#92 F/bulma product card
  client/components/AllProducts.js
  client/components/Cart.js
  client/components/ProductCard.js
  client/components/ProductCard.spec.js
  client/components/testData.js
  public/images/glitter.jpg
  public/images/wings.jpg
  public/style.css
  script/seed.js
Labels: in progress

#95 F/single product
  client/components/ProductCard.js
  client/components/SingleProduct.js
  client/components/SingleProduct.spec.js
  client/components/index.js
  client/routes.js
  client/store/index.js
  client/store/singleProduct.js
  client/utils/index.js
  package-lock.json
  package.json
  public/style.css
  script/seed.js
  server/api/products.js
  server/index.js
Labels: help wanted

#98 F/cart backend
  client/components/AuthForm.js
  public/style.css
Labels: in progress

#104 fix: moving lorem hipsum to reg dependencies for heroku
  package.json
Labels: in progress

#114 feat: changed a links to React-Router-Dom Links
  client/components/Navbar.js
Labels: help wanted

#115 B/seed issue
  client/components/AllProducts.spec.js
  client/components/ProductCard.spec.js
  client/components/SingleProduct.spec.js
  client/components/testData.js
  client/store/cart.spec.js
  client/store/products.spec.js
  package-lock.json
  package.json
  server/api/products.js
  server/api/products.spec.js
  server/db/models/order.spec.js
  server/db/models/product.js
  server/db/models/product.spec.js
Labels: help wanted

#116 F/order products update
  server/db/models/index.js
  server/db/models/order.js
  server/db/models/order.spec.js
  server/db/models/orderProduct.js
Labels: in progress

#117 F/navbar user
  client/components/Navbar.js
  client/components/Navbar.spec.js
  client/utils/index.js
Labels: in progress

#119 F/cart backend for real
  client/components/AllProducts.js
  client/components/Cart.js
  client/components/Navbar.js
  client/components/ProductCard.js
  client/routes.js
  client/store/cart.js
  client/store/user.js
  client/utils/index.js
  script/seed.js
  server/api/users.js
  server/auth/google.js
  server/db/models/user.js
Labels: help wanted

#128 F/order quantity
  script/seed.js
  server/db/models/order.js
  server/db/models/order.spec.js
  server/db/models/orderProduct.js
  server/db/models/product.js
Labels: help wanted

#136 F/quantity stuff
  client/components/Cart.js
  client/components/Navbar.js
Labels: in progress

#138 fix: quantity bug
  client/components/Cart.js
Labels: in progress

#144 F/product actions component
  client/components/AllProducts.js
  client/components/AuthForm.js
  client/components/Cart.js
  client/components/Navbar.js
  client/components/ProductActions.js
  client/components/ProductCard.js
  client/components/ProductCard.spec.js
  client/components/SingleProduct.js
  client/utils/index.js
  package-lock.json
  package.json
  public/style.css
  script/seed.js
  server/api/products.js
Labels: in progress

#151 F/save local cart upon login
  client/store/cart.js
  server/api/users.js
Labels: in progress

#155 F/order checkout
  client/components/Cart.js
  client/components/ProductActions.js
  client/components/ProductCard.js
  client/components/SingleProduct.js
  client/store/cart.js
  client/utils/index.js
  public/style.css
Labels: in progress

#160 fix: added /seed to seed images
  script/seed.js
Labels: in progress

#162 feat: local state on cart component for confirmation message
  client/components/Cart.js
Labels: in progress

#165 fix: update quantity button for logged in users
  client/store/cart.js
  server/api/users.js
Labels: help wanted

#164 F/cart delete
  client/components/AllProducts.js
  client/components/ProductActions.js
  client/components/ProductCard.js
  client/store/cart.js
  client/utils/index.js
  server/api/users.js
Labels: help wanted

#167 fix: supress redux logger for production environment
  client/store/index.js
Labels: in progress

#168 Test cleanup
  client/components/AllProducts.spec.js
  client/components/Cart.js
  client/components/Cart.spec.js
  client/components/Navbar.js
  client/components/Navbar.spec.js
  client/components/ProductCard.js
  client/components/ProductCard.spec.js
  client/components/SingleProduct.js
  client/components/SingleProduct.spec.js
  client/store/cart.spec.js
  client/utils/index.js
  server/api/users.spec.js
Labels: help wanted

#172 F/stripe
  client/components/Cart.js
  client/components/CheckoutForm.js
  client/index.js
  public/style.css
  server/api/charge.js
Labels: in progress

#170 F/post routes
  client/socket.js
  server/api/users.js
  server/auth/index.js
Labels: in progress

#173 feat: all products loading indicator and console log cleanup
  client/components/AllProducts.js
  client/components/CheckoutForm.js
Labels: in progress

#174 fix: fixed duplicate products in all products
  client/components/AllProducts.js
Labels: in progress

#177 remove cart loading indicator
  client/components/Cart.js
Labels: in progress

#178 fix: reference error in auth/me
  server/auth/index.js
Labels: in progress
